### PR TITLE
New association year, new secretary

### PR DESCRIPTION
**Pull request by tomudding**
# Description

It is July 11 (GH-309), so it is time for another update to the renewal emails. Update the sender in renewal emails to Jens, the secretary for 2024-2025.

I am still against having the names hard-coded in the e-mails, but as previously discussed in GH-286 we do not have a better way of doing this (yet).

## Types of changes

- [ ] Bug fix _(non-breaking change which fixes an issue)_
- [ ] New feature _(non-breaking change which adds functionality)_
- [ ] Breaking change _(fix or feature that would cause existing functionality to change)_
- [ ] Documentation improvement _(no changes to code)_
- [X] Other _(please specify)_

### CODE REVIEW

**Comment by rinkp** [comment]
GH-390 to the rescue?

**Comment by tomudding** [comment]
> [GH-390](https://github.com/GEWIS/gewisdb/pull/390) to the rescue?
> 
> In the long run that will require a frontend but in the meantime it can still be better to edit it in the database instead of in the code.

I have been thinking about this for a few weeks, and at first, I only saw new problems. However, this will work because of the existing exception handling:
https://github.com/GEWIS/gewisdb/blob/4692ad98bbb7d8967c7f7ea18cf207fc98f2a240/module/Checker/src/Service/Renewal.php#L52-L60

I will modify this PR to move to the configuration service but will not implement a UI for it.

**Comment by tomudding** [comment]
The 'ready for review' button just disappeared, that is rather unfortunate

**Comment by tomudding** [comment]
Adjusted based on our earlier discussions of not wanting to hardcode anything. Moving it to the dynamic configuration was an option but still requires someone to make the appropriate changes at the right time; that is an assumption we should not want to make.

Further adjustments were made based on feedback from the board.

**Review by rinkp — APPROVED** [review]

**Pull request merged**
