### PR TITLE
Implement active members & organ membership API endpoints

### PR DESCRIPTION
**Pull request by rinkp**
Upon merging closes GH-262

To do:
* [x] Migrate to report DB
* [x] Implement active member endpoints
* [x] Show organ membership

### CODE REVIEW

**Comment by rinkp** [comment]
For some reason I get the normal authentication op `/api/members` so I hope psalm or phpstan in GitHub might find the error

**Comment by tomudding** [comment]
Because we now exclusively use `Report` for the APIs we can consider moving everything to the `Report` module (probably the `Query` stuff too) but it is not (yet) necessary.

**Review by tomudding — APPROVED** [review]
I still do not know why PHPStan fails but everything else looks good and works as expected.

**Comment by rinkp** [comment]
> Because we now exclusively use `Report` for the APIs we can consider moving everything to the `Report` module (probably the `Query` stuff too) but it is not (yet) necessary.

I was thinking about this and I don't think we should do that completely, especially if read-write access is a thing

**Comment by tomudding** [comment]
> > Because we now exclusively use `Report` for the APIs we can consider moving everything to the `Report` module (probably the `Query` stuff too) but it is not (yet) necessary.
> 
> I was thinking about this and I don't think we should do that completely, especially if read-write access is a thing

True, did not think about the writeable part of the API.

**Pull request merged**
