### PR TITLE
Improve machine-readability of `openapi.yaml`

### PR DESCRIPTION
**Pull request by rinkp**
# Description
* Fixes one inconsistency in the API response
* Improves machine-readability of `openapi.yaml` by giving objects titles, reusing objects and reducing the number of models

## Types of changes

- [ ] Bug fix _(non-breaking change which fixes an issue)_
- [ ] New feature _(non-breaking change which adds functionality)_
- [ ] Breaking change _(fix or feature that would cause existing functionality to change)_
- [x] Documentation improvement _(no changes to code)_
- [ ] Other _(please specify)_

### CODE REVIEW

**Comment by rinkp** [comment]
@JustSamuel

**Review by tomudding — APPROVED** [review]
I am merely a human, so I wondered whether I was in the best position to review the spec's machine-readability. As such, I asked a computer program to check the specs too, and we both agreed that it could successfully produce an API client (and is thus correctly formatted and interpreted).

**Comment by tomudding** [comment]
@JustSamuel @Yoronex please review...

**Review by Yoronex — APPROVED** [review]
lgtm, but I am not familiar with the GEWISDB-SudoSOS integration, so I prefer @JustSamuel to also take a look.

**Review by JustSamuel — APPROVED** [review]

**Pull request merged**
