### PR TITLE
Typing of forms (fixes GH-366)

### PR DESCRIPTION
**Pull request by rinkp**
GH-367 was automatically closed upon branch rename, opening again

- [x] Fix existing `Form`s to remove all psalm warnings
- [x] Decide on inherited form typing
- [ ] Add type hints to all forms
  - [x] module/Database/src/Form/Abolish.php
  - [x] module/Database/src/Form/AbstractDecision.php
  - [x] module/Database/src/Form/Budget.php
  - [x] module/Database/src/Form/Destroy.php
  - [x] module/Database/src/Form/Export.php
  - [x] module/Database/src/Form/MemberLists.php
  - [x] module/Database/src/Form/MemberType.php
  - [x] module/Database/src/Form/Query.php
  - [x] module/Database/src/Form/QueryExport.php
  - [x] module/Database/src/Form/QuerySave.php
  - [x] module/Database/src/Form/Board/Discharge.php
  - [x] module/Database/src/Form/Board/Install.php
  - [x] module/Database/src/Form/Board/Release.php
  - [x] module/User/src/Form/ApiPrincipal.php
  - [x] module/User/src/Form/Login.php
  - [x] module/User/src/Form/UserCreate.php
  - [x] module/User/src/Form/UserEdit.php
  - [ ] module/Database/src/Form/Address.php
  - [ ] module/Database/src/Form/CreateMeeting.php
  - [ ] module/Database/src/Form/DeleteAddress.php
  - [ ] module/Database/src/Form/DeleteDecision.php
  - [ ] module/Database/src/Form/DeleteList.php
  - [ ] module/Database/src/Form/Export.php
  - [ ] module/Database/src/Form/Foundation.php
  - [ ] module/Database/src/Form/Install.php
  - [ ] module/Database/src/Form/InstallationFunction.php
  - [x] module/Database/src/Form/MailingList.php
  - [x] module/Database/src/Form/Member.php
  - [ ] module/Database/src/Form/MemberApprove.php
  - [ ] module/Database/src/Form/MemberEdit.php
  - [ ] module/Database/src/Form/MemberExpiration.php
  - [ ] module/Database/src/Form/MemberLists.php
  - [ ] module/Database/src/Form/MemberRenewal.php
  - [ ] module/Database/src/Form/MemberType.php
  - [ ] module/Database/src/Form/OrganRegulation.php
  - [ ] module/Database/src/Form/Other.php
  - [ ] module/Database/src/Form/AuditEntry/AuditNote.php
  - [ ] module/Database/src/Form/Key/Grant.php
  - [ ] module/Database/src/Form/Key/Withdraw.php

### CODE REVIEW

**Comment by rinkp** [comment]
@tomudding , I am inclined to say that this error is a bug in Psalm:

```
ERROR: NoValue - module/User/src/Service/ApiPrincipalService.php:54:17 - All possible types for this return were invalidated - This may be dead code (see https://psalm.dev/179)
                return ApiPermissions::from($p);
```

**Comment by tomudding** [comment]
> @tomudding , I am inclined to say that this error is a bug in Psalm:
> 
> ```
> ERROR: NoValue - module/User/src/Service/ApiPrincipalService.php:54:17 - All possible types for this return were invalidated - This may be dead code (see https://psalm.dev/179)
>                 return ApiPermissions::from($p);
> ```

Psalm thinks the following about `$data['permissions']`:

```
array<array-key, class-string<User\Model\Enums\ApiPermissions>>
```

Because of that it correctly infers that there are no possible options left. However, the issue lies with `enum-string`. It does not do what you expect it to do. It is a `class-string` but specifically for enums. What you want to use is `value-of`:

```php
/**
 * @psalm-type ApiPrincipalFormType = array{
 *     description: string,
 *     token: string,
 *     permissions: value-of<ApiPermissions>[],
 * }
 *
 * @extends Form<ApiPrincipalFormType>
 */
class ApiPrincipal extends Form implements InputFilterProviderInterface
```

Now the type is correctly inferred:

```
array<array-key, '*'|'health_read'|'members_active_read'|'members_read'|'members_read_keyholder'|'members_read_type'|'organs_members_read'>
```

---

In this specific case, we should also change how we get the data from the form (to be very explicity we want our type back and not an `object`):

```diff
@@ -1 +1 @@
- $data = $form->getData();
+ $data = $form->getData(FormInterface::VALUES_AS_ARRAY);
```

---

Note that the `@template TFilteredValues` does not have to be present on our forms (unless we start using it for something).

**Comment by rinkp** [comment]
Although child form types technically can have less fields, I propose to let the typing require at least the same amount of fields for subforms such that you have to manually change the parent if this is not the case which prevents mistakes. Currently, all `Form`s seem to be that way

That would give you 
```php
/**
 * @template QueryFormTypeTemplate of QueryFormType & array<array-key,string>
 *
 * @psalm-type QueryFormType = array{
 *  'query': string,
 * }
 * @extends Form<QueryFormTypeTemplate>
 */
class Query extends Form implements InputFilterProviderInterface
```

which can have a subtype as follows: 
```php
/**
 * @psalm-import-type QueryFormType from Query
 * @psalm-type QuerySaveFormType = array{
 *  'name': string,
 * }
 * @extends Query<QueryFormType & QuerySaveFormType>
 */
class QuerySave extends Query implements InputFilterProviderInterface
{
```

**Comment by rinkp** [comment]
@tomudding , do you have any suggestions on these errors that appear - randomly to me - in some classes and not in others?

In `Abolish` PSalm seems to think everything is fine:
image

In `Discharge` which uses the same structure, this apparently is not good:
image

**Comment by rinkp** [comment]
@tomudding , shall we proceed like this? It will probably cause the other 22 typings to go into a small number of the files, but I cannot get it to work with proper imports, neither in psalm nor in phpstan

**Comment by tomudding** [comment]
> @tomudding , shall we proceed like this? It will probably cause the other 22 typings to go into a small number of the files, but I cannot get it to work with proper imports, neither in psalm nor in phpstan

Yes, I agree that this seems like the best way to fix it. Thank you for all your hard work in trying to get this to work properly!

**Review by tomudding — COMMENTED** [review]
> @tomudding , shall we proceed like this? It will probably cause the other 22 typings to go into a small number of the files, but I cannot get it to work with proper imports, neither in psalm nor in phpstan

Yes, I agree that this seems like the best way to fix it. Thank you for all your hard work in trying to get this to work properly!

**Comment by rinkp** [comment]
Considering that we were already performing a workaround for the typing, I now run into issues where typings are not properly recognised by factories (because there is a different between the type and its alias). Admittedly, it would help with verifying `->getData()` values, because when typing is incorrect it will complain. 
I don't think with typing it like this, we will achieve clarity and much help from Psalm, but only run into issues in the future. 
Therefore, I propose to not type the forms

**Pull request closed without merging**
