### PR TITLE
Updated dependencies

### PR DESCRIPTION
**Pull request by Koen1999**
It's just another regular jump. I did not update `doctrine/orm` since you mentioned we were waiting for a patch. Originally I wanted to update the service manager as well, but there are other dependencies that require modifications first.

### CODE REVIEW

**Review by tomudding — APPROVED** [review]
Works as expected.

**Comment by tomudding** [comment]
@Koen1999 I cannot merge this unless you sign the commit (and force push the updated/new commit), can you do this?

**Comment by Koen1999** [comment]
@tomudding, I hereby present: **A verified commit**

**Comment by tomudding** [comment]
@Koen1999 <3

**Pull request merged**
