### PR TITLE
Upgrade to PHP 8.2.0

### LINKED ISSUE #212: Upgrade to PHP 8.2
On December 8, 2022 PHP 8.2 will be released. There are a few things that should be checked before hand:

- no dynamic properties (I do not think we use this),
- removing partially callables (mostly used for callbacks in forms) as they are deprecated,
- ensuring correct return types when returning new instances of `DateTime(Immutable)`, and
- removing incorrect string interpolation of the form `"${some_variable}"` (but I do not think we use this).

Additionally, we have constructors that look like this:

```php
class SomeClass
{
    public function __construct(
        private readonly SomeType $var,
        private readonly AnotherType $anotherVar,
    ) {
    }

    // (...)
```

They can be changed to (only works for classes of which all properties are `readonly`):

```php
readonly class SomeClass
{
    public function __construct(
        private SomeType $var,
        private AnotherType $anotherVar,
    ) {
    }

    // (...)
```

### PR DESCRIPTION
**Pull request by tomudding**
Closes #212.

Blocking dependencies:
- None

Upgradable dependencies:
- `doctrine/doctrine-module` can be upgraded from 5.2.1 to 5.3.0
- `doctrine/doctrine-orm-module` can be upgraded to 5.3.0
- `laminas/laminas-component-installer` can be upgraded from 2.8.0 to 3.1.0
- `laminas/laminas-developer-tools` can be upgraded from 2.5.0 to 2.6.0
- `slam/phpstan-laminas-framework` can be upgraded to 1.4.0
- `friendsofphp/php-cs-fixer` (no update announced, should be bypassed with environment variable)

### CODE REVIEW

**Comment by tomudding** [comment]
`friendsofphp/php-cs-fixer` likely will not get proper support for PHP 8.2 soon, so for the GitHub Actions we can use `PHP_CS_FIXER_IGNORE_ENV`.

**Comment by Koen1999** [comment]
> `friendsofphp/php-cs-fixer` likely will not get proper support for PHP 8.2 soon, so for the GitHub Actions we can use `PHP_CS_FIXER_IGNORE_ENV`.

I know you are always very enthusiastic about the new PHP features, but it doesn't hurt to wait sometimes.
The current PHP version is still receiving security updates ;)

**Comment by tomudding** [comment]
> > `friendsofphp/php-cs-fixer` likely will not get proper support for PHP 8.2 soon, so for the GitHub Actions we can use `PHP_CS_FIXER_IGNORE_ENV`.
> 
> I know you are always very enthusiastic about the new PHP features, but it doesn't hurt to wait sometimes. The current PHP version is still receiving security updates ;)

I have no intention to just merge this the second every dependency is updated, especially not for GEWISDB. `php-cs-fixer` is used in `dry-run` mode in one of the actions to pump out some additional CS info (we do not do this in GEWISWEB, perhaps we should change that, create a set of actions that both repositories can use, kinda like a `gewisphp-coding-standards` repository), so that would also be the only place we use that environment variable.

**Comment by tomudding** [comment]
Tested locally, including with PHPStan and Psalm. All errors have been resolved and the baselines updated where necessary. All appears to be well, nothing is broken as the upgrade to PHP 8.2 was very minimal.

The two failing actions are due to the incompatible composer.json on master.

**Pull request merged**
