### PR TITLE
Grammar graduate renewal

### PR DESCRIPTION
**Pull request by rinkp**
What should we do without former secretaries paying attention

### CODE REVIEW

**Review by tomudding — APPROVED** [review]

**Comment by tomudding** [comment]
Interesting that the auto-merge disabled itself, the commit is signed.

**Comment by rinkp** [comment]
> Interesting that the auto-merge disabled itself, the commit is signed.

But not by @BorBorBor so that might be an issue

**Comment by tomudding** [comment]
> > Interesting that the auto-merge disabled itself, the commit is signed.
> 
> But not by @BorBorBor so that might be an issue

You enabled the auto-merge, so you will be the committer but regardless of that the commit will be signed by the GitHub key. If they look at the author it would be a bit weird.

**Comment by BorBorBor** [comment]
Lmao happy to help

**Pull request merged**
